### ISSUE TITLE
Suggestion: Clear survey-in observation time with disableSurveyMode()

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_u-blox_GNSS_v3#15]
Hi @PaulZC, 

I've done some testing with starting and stopping the survey-in procedure and noticed that the observation time does not get reset when `.disableSurveyMode()` is called. A minor suggestion that the function clears the value of `dur` in UBX-NAV-SVIN when called.

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),

AFAIAA there is no way to set ```dur``` to zero. I think only starting a new survey does that. I can't see a way to clear it using CFG-TMODE5 or the Configuration Interface. And you can't set it to zero with NAV-SVIN...

Sorry, I'm closing this one because I don't think we can implement it,
Paul
